library(httr)
library(twitteR)
library(base64enc)
library(tm)
library(wordcloud)
library(tidytext)
library(dplyr)
my.key <- "sIt6bR0ZhIOU1Wihg6ZzvfsDP"
my.secret <- "GfXF9wqrd3aQv2doyMeKrDOD2jX9o731Yje7wM5lN8xnJTENd5"
my.token <- "3090034427-p8M9M5faE0eIIw20K2TylMucKN69VStk9FVcDe1"
my.accesssecret <- "UHm3TxpHGxjTEndnfnPIwNixohc36YaqJWxuwxMWkiq3u"
setup_twitter_oauth(my.key,my.secret,my.token,my.accesssecret)
bigdata <- searchTwitter("#warszawa", n=100)
bigdata2.df <- do.call(rbind, lapply(bigdata, as.data.frame))
bigdata_list <- sapply(bigdata, function(x) x$getText())
bigdata_corpus <- Corpus(VectorSource(bigdata_list))
bigdata_corpus <- tm_map(bigdata_corpus, tolower)
bigdata_corpus <- tm_map(bigdata_corpus, removePunctuation)
bigdata_corpus <- tm_map(bigdata_corpus,function(x)removeWords(x,stopwords()))
wordcloud(bigdata_corpus)
bigdata.tdm <- TermDocumentMatrix(bigdata_corpus)
findFreqTerms(bigdata.tdm, lowfreq=5)
findAssocs(bigdata.tdm, 'warszawa', 0.50)
bigdata2.tdm <-removeSparseTerms(bigdata.tdm, sparse=0.90)

bigdata2.df <- tidy(bigdata2.tdm)
bigdata2.df <- as.data.frame(bigdata2.df)
bigdata2.df$term <-as.numeric(bigdata2.df$term)
bigdata2.df$document <- as.numeric(bigdata2.df$document)
bigdata2.df.scale <- scale(c(bigdata2.df$count,bigdata2.df$document))
bigdata.dist <- dist(bigdata2.df.scale, method = "euclidean")
bigdata.fit <- hclust(bigdata.dist, method="ward")
plot(bigdata.fit, main="Cluster - Cmentarz")
groups <- cutree(bigdata.fit, k=20)
rect.hclust(bigdata.fit, k=20, border="blue")